# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBxbATiMB2KGLH6rHs9xOkVDFYTU_zPQ
"""

import cv2
import os
import zipfile
import matplotlib.pyplot as plt

# Path to your dataset zip file
dataset_path = '/content/car detection.zip'
extract_dir = '/content/extracted_images'

# Extract the zip file contents
with zipfile.ZipFile(dataset_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Recursively find all image files inside the extracted folder
image_files = []
for root, dirs, files in os.walk(extract_dir):
    for file in files:
        if file.endswith(('.jpg', '.jpeg', '.png')):
            image_files.append(os.path.join(root, file))

# Initialize ORB detector
orb = cv2.ORB_create()

# Loop through a few images to display keypoints
for i, image_path in enumerate(image_files[:5]):  # Show for first 5 images
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Detect ORB keypoints
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    orb_image = cv2.drawKeypoints(image, keypoints, None, color=(0, 255, 0), flags=0)

    # Show the result
    plt.figure(figsize=(10, 6))
    plt.imshow(cv2.cvtColor(orb_image, cv2.COLOR_BGR2RGB))
    plt.title(f'ORB Feature Detection - {os.path.basename(image_path)}')
    plt.axis('off')
    plt.show()

import cv2
import os
import zipfile
import matplotlib.pyplot as plt

# Path to your zip file and extraction folder
dataset_path = '/content/car detection.zip'
extract_dir = '/content/extracted_images'

# Extract the zip file
with zipfile.ZipFile(dataset_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Recursively find all image files
image_files = []
for root, dirs, files in os.walk(extract_dir):
    for file in files:
        if file.endswith(('.jpg', '.jpeg', '.png')):
            image_files.append(os.path.join(root, file))

# Apply Gaussian Blur and display
for i, image_path in enumerate(image_files[:5]):  # Show first 5 images
    image = cv2.imread(image_path)
    blurred = cv2.GaussianBlur(image, (5, 5), 0)  # Apply Gaussian Blur

    # Show original and blurred images side-by-side
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title(f'Original - {os.path.basename(image_path)}')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor(blurred, cv2.COLOR_BGR2RGB))
    plt.title('Gaussian Blurred')
    plt.axis('off')

    plt.show()
import cv2
import os
import zipfile
import matplotlib.pyplot as plt

# Path to your zip file and extraction folder
dataset_path = '/content/car detection.zip'
extract_dir = '/content/extracted_images'

# Extract the zip file
with zipfile.ZipFile(dataset_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Recursively find all image files
image_files = []
for root, dirs, files in os.walk(extract_dir):
    for file in files:
        if file.endswith(('.jpg', '.jpeg', '.png')):
            image_files.append(os.path.join(root, file))

# Apply Histogram Equalization to grayscale images
for i, image_path in enumerate(image_files[:5]):  # Show for first 5 images
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply histogram equalization
    equalized = cv2.equalizeHist(gray)

    # Show original and equalized images side-by-side
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(gray, cmap='gray')
    plt.title(f'Original Grayscale - {os.path.basename(image_path)}')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(equalized, cmap='gray')
    plt.title('Histogram Equalized')
    plt.axis('off')

    plt.show()
import cv2
import os
import zipfile
import matplotlib.pyplot as plt
import numpy as np

# Path to your zip file and extraction folder
dataset_path = '/content/car detection.zip'
extract_dir = '/content/extracted_images'

# Extract the zip file
with zipfile.ZipFile(dataset_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Recursively find all image files
image_files = []
for root, dirs, files in os.walk(extract_dir):
    for file in files:
        if file.endswith(('.jpg', '.jpeg', '.png')):
            image_files.append(os.path.join(root, file))

# Perspective Transform on first few images
for i, image_path in enumerate(image_files[:3]):  # Limit for demo
    image = cv2.imread(image_path)
    h, w = image.shape[:2]

    # Define 4 source points (corners from an angled area)
    src_pts = np.float32([
        [w * 0.1, h * 0.3],  # Top-left
        [w * 0.9, h * 0.3],  # Top-right
        [w * 0.05, h * 0.9], # Bottom-left
        [w * 0.95, h * 0.9]  # Bottom-right
    ])

    # Define 4 destination points for top-down view
    dst_pts = np.float32([
        [0, 0],
        [w, 0],
        [0, h],
        [w, h]
    ])

    # Get perspective transform matrix and apply it
    matrix = cv2.getPerspectiveTransform(src_pts, dst_pts)
    warped = cv2.warpPerspective(image, matrix, (w, h))

    # Show original and warped (top-down) images
    plt.figure(figsize=(12, 6))

    plt.subplot(1, 2, 1)
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title('Original (Angled View)')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor(warped, cv2.COLOR_BGR2RGB))
    plt.title('Perspective Transformed (Top-Down View)')
    plt.axis('off')

    plt.show()
import cv2
import numpy as np
from matplotlib import pyplot as plt

def show_img(img, title="Image", cmap='gray'):
    plt.figure(figsize=(10, 6))
    if len(img.shape) == 2:
        plt.imshow(img, cmap=cmap)
    else:
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.axis('off')
    plt.show()

def process_frame(frame):
    frame = cv2.resize(frame, (640, 480))
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    hist_eq = cv2.equalizeHist(blurred)

    orb = cv2.ORB_create()
    keypoints, _ = orb.detectAndCompute(hist_eq, None)
    features = cv2.drawKeypoints(frame, keypoints, None, color=(0, 255, 0))

    edges = cv2.Canny(hist_eq, 100, 200)
    return frame, features, edges

# -------- Change this to True if you want to process a video --------
use_video = False
path = '/content/photo.png' if not use_video else '/content/video.mp4'

if not use_video:
    img = cv2.imread(path)
    if img is not None:
        orig, features, edges = process_frame(img)
        show_img(orig, "Original Image")
        show_img(features, "ORB Feature Detection")
        show_img(edges, "Canny Edge Detection")
    else:
        print("Error: Could not load image.")
else:
    cap = cv2.VideoCapture(path)
    for i in range(5):  # Process first 5 frames
        ret, frame = cap.read()
        if not ret:
            break
        orig, features, edges = process_frame(frame)
        show_img(orig, f"Frame {i} - Original")
        show_img(features, f"Frame {i} - ORB")
        show_img(edges, f"Frame {i} - Edges")
    cap.release()
import cv2
import os
import zipfile
import matplotlib.pyplot as plt

# Path to your zip file and extraction folder
dataset_path = '/content/car detection.zip'
extract_dir = '/content/extracted_images'

# Extract the zip file
with zipfile.ZipFile(dataset_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Recursively find all image files
image_files = []
for root, dirs, files in os.walk(extract_dir):
    for file in files:
        if file.endswith(('.jpg', '.jpeg', '.png')):
            image_files.append(os.path.join(root, file))

# Apply Canny Edge Detection to first few images
for i, image_path in enumerate(image_files[:5]):
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply Gaussian blur to reduce noise before edge detection
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)

    # Apply Canny Edge Detection
    edges = cv2.Canny(blurred, threshold1=50, threshold2=150)

    # Show original and edges side-by-side
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title(f'Original - {os.path.basename(image_path)}')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(edges, cmap='gray')
    plt.title('Canny Edge Detection')
    plt.axis('off')

    plt.show()
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Define helper function
def show_img(img, title="Image"):
    plt.figure(figsize=(10, 6))
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.axis('off')
    plt.show()

# Load image
image_path = '/content/photo.png'
image = cv2.imread(image_path)
if image is None:
    print("Image not found.")
else:
    image = cv2.resize(image, (900, 600))
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Manual parking slot coordinates (x, y, w, h) — update based on your image
    parking_slots = [
        (100, 100, 80, 160),
        (200, 100, 80, 160),
        (300, 100, 80, 160),
        (400, 100, 80, 160),
        (500, 100, 80, 160)
    ]

    empty_count = 0
    for (x, y, w, h) in parking_slots:
        roi = gray[y:y+h, x:x+w]
        mean_val = np.mean(roi)

        if mean_val > 110:  # adjust threshold based on lighting
            color = (0, 0, 255)  # Red for empty
            empty_count += 1
        else:
            color = (0, 255, 0)  # Green for occupied

        cv2.rectangle(image, (x, y), (x+w, y+h), color, 2)

    print(f"Empty slots detected: {empty_count}/{len(parking_slots)}")
    show_img(image, "Parking Slot Status")